service: sandbox-serverless-babel

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: src/app/handlers.hello
    events:
      - http:
          method: get
          path: hello
          integration: lambda
  bye:
    handler: src/app/handlers.bye
    events:
      - http:
          method: get
          path: bye
          integration: lambda
